<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
<!--===================== Defining parameters depend on angle =====================-->
    <xacro:if value="${omni_angle == 15}">
        <xacro:property name="leg_x_offset" value="${0.007893980876}"/>
        <xacro:property name="leg_y_offset" value="${0.1594607377}"/>
    </xacro:if>
    <xacro:if value="${omni_angle == 30}">
        <xacro:property name="leg_x_offset" value="${0.02825}"/>
        <xacro:property name="leg_y_offset" value="${0.1789304353}"/>
    </xacro:if>
    <xacro:if value="${omni_angle == 45}">
        <xacro:property name="leg_x_offset" value="${0.04631549417}"/>
        <xacro:property name="leg_y_offset" value="${0.1763154942}"/>
    </xacro:if>
<!--=========================================== Defining parameters ===========================================-->
    <xacro:macro name="leg" params="prefix num side cur_ang">
      <!--===================== Link description =====================-->
      <link name="leg_${prefix}_${num}">
        <inertial>
                <xacro:if value="${leg_height == 0}">
                    <mass value="${0.010307884}"/>
                    <origin rpy="${0} 0 0" xyz="${-0.008963344} ${0} ${-0.020168668}"/>
                    <inertia
                            ixx="0.000004032" ixy="0" ixz="0.000000712"
                            iyy="0.000004993" iyz="0"
                            izz="0.000001071"/>
                </xacro:if>
                <xacro:if value="${leg_height == 1}">
                    <mass value="${0.012706347}"/>
                    <origin rpy="${0} 0 0" xyz="${-0.013348671} ${0} ${-0.027584119}"/>
                    <inertia
                            ixx="0.000007895" ixy="0" ixz="0.000001300"
                            iyy="0.000009763" iyz="0"
                            izz="0.000002004"/>
                </xacro:if>
        </inertial>
            <collision>
                <origin rpy="0  0  0" xyz="0 0 0"/>
                <geometry>
                    <xacro:if value="${leg_height == 0}">
                        <mesh filename="package://strirus_cad_design/stl/collision/leg_55.stl" scale="1 1 1"/>
                    </xacro:if>
                    <xacro:if value="${leg_height == 1}">
                        <mesh filename="package://strirus_cad_design/stl/collision/leg_70.stl" scale="1 1 1"/>
                    </xacro:if>
                </geometry>
            </collision>
            <visual>
                <origin rpy="0  0  0" xyz="0 0 0"/>
                <geometry>
                    <xacro:if value="${leg_height == 0}">
                        <mesh filename="package://strirus_cad_design/stl/visual/leg_55.stl" scale="1 1 1"/>
                    </xacro:if>
                    <xacro:if value="${leg_height == 1}">
                        <mesh filename="package://strirus_cad_design/stl/visual/leg_70.stl" scale="1 1 1"/>
                    </xacro:if>
                </geometry>
                <material name="white"/>
            </visual>
      </link>
      <!--===================== Joint description =====================-->
      <joint name="leg_${prefix}_${num}_revolute_joint" type="revolute">
        <child link="leg_${prefix}_${num}"/>
          <!--=================== Body and leg =====================-->
          <xacro:if value="${not(num >= amount_of_legs_one_part)}">
            <parent link="body_1_part"/>
                <xacro:if value="${num % 2 and omni_angle == 0}">
                    <origin rpy="0       ${deg2rad*cur_ang}        0"
                            xyz="${dist_btw_legs * (num % amount_of_legs_one_part)} ${0.1555*side}  ${0}"/>
                </xacro:if>
                <xacro:if value="${not (num % 2) and omni_angle == 0}">
                    <origin rpy="0       ${deg2rad*cur_ang}        0"
                            xyz="${dist_btw_legs * (num % amount_of_legs_one_part)} ${0.1385*side}  ${0}"/>
                </xacro:if>
                <xacro:if value="${omni_angle != 0}">
                    <origin rpy="0       ${deg2rad*cur_ang}        ${deg2rad*omni_angle * side}"
                            xyz="${-leg_x_offset + dist_btw_legs * (num % amount_of_legs_one_part)} ${leg_y_offset*side}  ${0}"/>
                </xacro:if>
          </xacro:if>
          <xacro:if value="${num >= amount_of_legs_one_part}">
            <parent link="body_2_part"/>
                <xacro:if value="${num % 2 and omni_angle == 0}">
                    <origin rpy="0       ${deg2rad*cur_ang}      0"
                            xyz="${dist_body_2_leg_count_point - dist_btw_legs * (num % amount_of_legs_one_part)} ${0.1555*side}  ${0}"/>
                </xacro:if>
                <xacro:if value="${not (num % 2) and omni_angle == 0}">
                    <origin rpy="0       ${deg2rad*cur_ang}        0"
                            xyz="${dist_body_2_leg_count_point - dist_btw_legs * (num % amount_of_legs_one_part)} ${0.1385*side}  ${0}"/>
                </xacro:if>
                <xacro:if value="${omni_angle != 0}">
                    <origin rpy="0       ${deg2rad*cur_ang}        ${-deg2rad*omni_angle * side}"
                            xyz="${leg_x_offset + dist_body_2_leg_count_point - dist_btw_legs * (num % amount_of_legs_one_part)} ${leg_y_offset*side}  ${0}"/>
                </xacro:if>
          </xacro:if>
            <!--=============== Joint properties ===============-->
            <axis xyz="0 -1  0"/>
            <limit effort="1.5" lower="-1e+5" upper="1e+5" velocity="3.0"/>
            <xacro:if value="${ideal_leg_motors == 1}">
                <joint_properties damping="0.0" friction="0.0"/>
            </xacro:if>
            <xacro:if value="${ideal_leg_motors == 0}">
                <joint_properties damping="0.0" friction="0.0"/>
            </xacro:if>
      </joint>
      <!--===================== Leg ytansmission description =====================-->
      <transmission name="tran_${num}">
        <type>transmission_interface/SimpleTransmission</type>
          <joint name="leg_${prefix}_${num}_revolute_joint">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
          </joint>
        	<actuator name="motor__${num}">
          	<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
          	<mechanicalReduction>10</mechanicalReduction>
        	</actuator>
      </transmission>

      <gazebo reference="leg_${prefix}_${num}">
            <material>Gazebo/Gray</material>
      </gazebo>
      <!-- ============ Fancy physics of robot ================ -->
      <xacro:if value="${leg_fancy_physics == 1}">
        <gazebo reference="leg_${prefix}_${num}">
          <collision>
            <surface>
              <bounce>
                <restitution_coefficient>0</restitution_coefficient>
                <threshold>100000</threshold>
              </bounce>
              <friction>
                <ode>
                  <mu>0.8</mu>
                  <mu2>0.8</mu2>
                  <slip1>0.2</slip1>
                  <slip2>0.2</slip2>
                </ode>
              </friction>
            </surface>
          </collision>
        </gazebo>
      </xacro:if>
    </xacro:macro>

    <xacro:if value="${str(angle_btw_legs) == 'specific'}">
        <xacro:property name="angle_seq_l_leg" value="${l_specific_angle_btw_legs.split(',')}"/>
        <xacro:property name="angle_seq_r_leg" value="${r_specific_angle_btw_legs.split(',')}"/>
    </xacro:if>
    <xacro:if value="${str(angle_btw_legs) != 'specific'}">
        <xacro:property name="range05" value="${[0,1,2,3,4,5]}"/>
        <xacro:property name="angle_seq_l_leg" value="${[(angle_for_0_l_leg + i * angle_btw_legs) for i in range05]}"/>
        <xacro:property name="angle_seq_r_leg" value="${[(angle_for_0_r_leg + i * angle_btw_legs) for i in range05]}"/>
    </xacro:if>


    <!--==================== Create needed number of legs (is implemented by recurcion) ====================-->
    <xacro:macro name="create_legs" params="prefix side number angle_seq">
        <xacro:leg prefix="${prefix}" num="${number}" side="${side}" cur_ang="${angle_seq[number]}"/>
        <xacro:if value="${number}">
            <xacro:create_legs number="${number-1}" prefix="${prefix}" side="${side}" angle_seq="${angle_seq}"/>
        </xacro:if>
    </xacro:macro>

    <xacro:create_legs prefix="left" side="1" number="${number_of_legs}" angle_seq="${angle_seq_l_leg}"/>
    <xacro:create_legs prefix="right" side="-1" number="${number_of_legs}" angle_seq="${angle_seq_r_leg}"/>
</robot>
